### ISSUE TITLE
Commands with same name in different modules call one handler

### ISSUE THREAD

**Issue by tsapko3628** [nestjs/cqrs#542] opened 2021-01-11 16:38 UTC
## I'm submitting a...
<pre><code>
[ ] Regression 
[+] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Two command classes with same name in different modules passed into CommandBus.execute.
Two different handlers for these commands in different modules. 
Then I pass one of these two commands, it always calls one handler.

## Expected behavior
Two different commands (aka different classes) calls their own command handlers. Command handlers detecting via constructor, not via constructor.name 

## What is the motivation / use case for changing the behavior?
I have CreateCommand in user module, which create user, and CreateCommand in ProductModule, which create product (for example). I don't want to call them CreateUserCommand and CreateProductCommand. Their have been already associate with them because they in named module. I want to call commands CreateCommand for both of them. 

## Environment

<pre><code>
Nest version: 7.5.1
Nest Cqrs version: 7.0.1
 
For Tooling issues:
- Node version: v12.19.0
- Platform:  Mac (Big Sur), Linux (Ubuntu 18.04)
</code></pre>

**Comment by tsapko3628** [comment] 2021-01-11 16:40
Fix this can also fix https://github.com/nestjs/cqrs/issues/487. I also have this bug (but i didn't check twice calling)

**Comment by kamilmysliwiec** [comment] 2021-01-12 09:00
Duplicate of https://github.com/nestjs/cqrs/issues/487

**Closed by kamilmysliwiec** 2021-01-12 09:00 UTC

**Comment by tsapko3628** [comment] 2021-01-12 14:52
Not duplicate. It's another case, but they are really similar. And I don't see any resolution for #487
